### ISSUE TITLE
Error: LWC1702: lwc => import {createElement} from 'lwc'; seems to be broken?

### ISSUE THREAD

**Issue by erocheleau** [salesforce/sfdx-lwc-jest#350] opened 2024-02-19 22:22 UTC
### Description

VSCode is just showing a cryptic error
![image](https://github.com/salesforce/sfdx-lwc-jest/assets/2488155/721b4e1a-a9c0-4af2-a018-705ed0749500)
on the line `import {createElement} from 'lwc';` where it wasn't before?

It looks like I can change it to `import {createElement} from '@lwc/engine-dom';` but I'm afraid it might cause other issues?

#### Steps to Reproduce

Even in the lwc-recipe repository I am having this error.

```js
import {createElement} from 'lwc';
```

#### Expected Results

No errors I guess?

#### Actual Results

![image](https://github.com/salesforce/sfdx-lwc-jest/assets/2488155/d4400590-909a-4dc9-8fc4-65982ca6e55d)

### Version

-   @salesforce/sfdx-lwc-jest: 3.1.2
-   Node: v18.19.0

The import in the jest files seems to resolve to this `.d.ts` from the `.sfdx` folder that gets created every time I run a sf command from inside the project for instance.

![image](https://github.com/salesforce/sfdx-lwc-jest/assets/2488155/998cbeb7-0cc6-4c2d-b051-6d806a3bb44b)

**Comment by nolanlawson** [comment] 2024-02-20 21:51
Thanks for reporting!

`import {createElement} from 'lwc'` is disallowed on platform due to [this ESLint rule](https://github.com/salesforce/eslint-plugin-lwc/blob/master/docs/rules/no-disallowed-lwc-imports.md). That said, people use it in their Jest tests all the time, and we don't have a problem with that.

Questions:

1. Are you using this in a Jest test or a component file?
2. Is this a new issue that popped up recently? What caused it?
3. What is this preventing you from doing? (E.g. publishing, running tests, etc.)

**Comment by erocheleau** [comment] 2024-02-21 14:21
> Thanks for reporting!
> 
> `import {createElement} from 'lwc'` is disallowed on platform due to [this ESLint rule](https://github.com/salesforce/eslint-plugin-lwc/blob/master/docs/rules/no-disallowed-lwc-imports.md). That said, people use it in their Jest tests all the time, and we don't have a problem with that.
> 
> Questions:
> 
> 1. Are you using this in a Jest test or a component file?

Yes that's what I meant, sorry if that wasn't clear. It's in all the Jest test files, following the example of tests given by Salesforce or other GitHub repos.

> 2. Is this a new issue that popped up recently? What caused it?

I don't have a specific cause for the issue unfortunately, I am part of multiple repositories, all running different versions of sfdx-lwc-jest. Could've been perhaps related to an update of the ESLint plugin?

> 3. What is this preventing you from doing? (E.g. publishing, running tests, etc.)

Enjoying my "error-less" files :) It's not blocking anything, but it's just annoying.

// @ts-ignore
doesn't even resolve it, but VSCode resolves the imports from 'lwc' to a typings file in `.sfdx/typings` IIRC, which doesn't have an exported `createElement` on it. 
Wondering if perhaps there should just be a typings file specific to the 'lwc' imported while writing lwc-Jest tests?

**Comment by BatemanVO** [comment] 2024-02-21 19:21
Adding that I also see this highlight in VSCode with sfdx-lwc-jest 4.0.1, even though running `npx eslint` on the directory won't actually throw any errors. If I had not seen this issue, I don't think I would've even noticed anything wrong.

I did try updating our `.eslintrc.json` file to include:
```
"@lwc/lwc/valid-api": ["error", { "allowList": ["createElement"] }]
```
but that didn't resolve the issue.

**Comment by nolanlawson** [comment] 2024-02-22 00:33
Thanks for the confirmation. So it sounds like this might actually be an issue purely in the VS Code Extension? It sounds like you are just seeing a red squiggly in the VS Code UI, but you can't actually reproduce the ESLint error by running `eslint` on the command line.

If that's the case, then this may have been due to a change in [lightning-language-server](https://github.com/forcedotcom/lightning-language-server) (which the VS Code extension uses).

**Comment by erocheleau** [comment] 2024-02-22 14:05
@nolanlawson perhaps, do you have any idea to try to hide this?

**Comment by nolanlawson** [comment] 2024-02-22 18:41
Based on the description above, I am closing this issue in favor of an issue on `forcedotcom/lightning-language-server`. Could you please provide your VS Code version, SFDX CLI version, and OS version in that thread? Thank you! 

New issue: https://github.com/forcedotcom/lightning-language-server/issues/588

**Closed by nolanlawson** 2024-02-22 18:41 UTC

**Comment by eschweitzer78** [comment] 2025-06-13 04:59
@nolanlawson, the suggested workaround to that problem is to replace the import and put `"@lwc/dom-engine"` instead of `"lwc"`. This does clear the errors in VS Code Studio.

**However**, once I do that in my setup (which has TypeScript activated), every jest test fails with an error indicating that my LWCs do no inherit from `LightningElement`... it's along the lines of

> X is not a valid component, or does not extends LightningElement from "lwc". You probably forgot to add the extend clause on the class declaration.

After a bit of tinkering, I found out that `LightningElement` is resolved differently between `sfdx-jest-lwc` and the transpiled TS LWC even though it's the same underlying code. One LightningElement comes from the `@lwc/engine-dom` module within `sdfx-lwc-jest`, whereas the other one comes from the sfdx project's `@lwc/engine-dom` module.

I think it's linked to the following bit of code in `resolver.js`:
```
module.exports = function (modulePath, options) {
    if (modulePath === 'lwc') {
        return require.resolve('@lwc/engine-dom');
    }
    return getModule(modulePath, options) || lwcResolver.apply(null, arguments);
};
```

I have patched it as follows and it solves the issue on my end:
```
module.exports = function (modulePath, options) {
    if (modulePath === 'lwc' || modulePath === '@lwc/engine-dom') {
        return require.resolve('@lwc/engine-dom');
    }
    return getModule(modulePath, options) || lwcResolver.apply(null, arguments);
};
```
