### ISSUE TITLE
Module missing when installing on a Docker image

### ISSUE THREAD

**Issue by renatoliveira** [salesforce/sfdx-lwc-jest#76] opened 2019-07-19 03:02 UTC
I'm attempting to generate an image with a couple of tools included, including `lwc-jest`.

The following Dockerfile gives me an image with the base stuff I want:

```Dockerfile
FROM alpine:3.10

RUN apk update
RUN apk add --no-cache wget nodejs yarn openjdk8 unzip openssl vim

RUN yarn global add sfdx-cli@7.14.0
RUN yarn global add @salesforce/lwc-jest@0.5.1
RUN yarn global add prettier prettier-plugin-apex
```

However, when running lwc-jest on the project's folder, I get an error for a specific test:

```
Cannot find module '@salesforce/wire-service-jest-util' from 'myComponent.test.js

  1 | import { createElement } from 'lwc';
  2 | import { getRecord } from 'lightning/uiRecordApi';
> 3 | import { registerLdsTestWireAdapter } from '@salesforce/wire-service-jest-util';
    | ^
```

And the same error happens if I change `wire-service-jest-util` to `lwc-jest`.

Funny thing is: if I use my favourite package manager's `install` command on the project's folder, then it detects the module and the test is run, although it still fails.

```
    expect(jest.fn()).toHaveBeenCalledTimes(1)

    Expected mock function to have been called one time, but it was called zero times.

  48 |     return Promise.resolve().then(() => {
> 49 |       expect(window.fetch).toHaveBeenCalledTimes(1);
```

The same test does not fail when `lwc-jest` is run locally. All tests are passing for the project.

On the Docker machine, the configuration is:

```
/sfdxproject # node --version && npm --version && lwc-jest --version
v10.16.0
6.10.1
0.5.1
```

On my local machine:

```
$ --version && npm --version && lwc-jest --version
v11.10.0
6.10.1
0.5.1
```

Node version is different, but should it really be outputing such different results?

**Comment by pmdartus** [comment] 2019-07-19 07:32
@renatoliveira would you mind sharing a repo with the docker image and the LWC code for us to reproduce the issue?

**Comment by renatoliveira** [comment] 2019-07-19 13:27
@pmdartus I've created [this repo](https://github.com/renatoliveira/lwc-jest-missing-module-demo) which should contain enough code to reproduce the issue.

The folder contains the Dockerfile used to build the image. To reproduce the missing module issue, please build the image and go to the sfdx project directory.

```
docker build -t toolkitimage .
docker run -it <image hash>

cd sfdxproject/
lwc-jest
```

This should output the "missing module" error.

If you `yarn add @salesforce/lwc-jest` then the test fails because of an assertion.

Then if you add it to the "test" section of the package.json, as in:

```
...
"scripts": {
    "test": "lwc-jest"
}
...
```

and run the test command with `yarn run test` the test will fail because of the assertion that expects `window.fetch` to be called once.

If I try to fix that test to use the mocking specified [here](https://github.com/trailheadapps/lwc-recipes/blob/bb2f9e4438ef28a7b061ba74a3fa0ff1b0af549b/force-app/main/default/lwc/miscRestApiCall/__tests__/miscRestApiCall.test.js#L59) then different things happen on my local machine and on the Docker image.

On the Docker image the test will fail because `fetch` was not called (same previous error), while locally the test fails because of a "cannot read property 'then' of undefined", while running `fetch` and calling one of its promises callbacks:

```
TypeError: Cannot read property 'then' of undefined

      35 |     }
      36 | 
    > 37 |     fetch(this.url + '/' + args, {
         |     ^
      38 |       method: 'GET',
      39 |       headers: {},
      40 |       mode: 'cors',
```

And I'm not sure why this is happening. It should work because the adapter is emitting the record data. It doens't call the error callback on the component, and passes the field's value, because it exists. So `fetch` should be called.

I've added a couple more of the tests variants to the repository. This time, if you build the image, cd into the project, and run `yarn run test` from the start, all of them fail with the module missing error. After `yarn add @salesforce/lwc-jest` one of them passes (myComponent.test.js), but all the others fail for different reasons.

---

I'm really confused, and I can't understand why the first test passes, but test number '4' doesn't, for example.

**Comment by trevor-bliss** [comment] 2019-07-19 23:58
Hi @renatoliveira. Firstly, you should be importing `registerLdsTestWireAdapter` from `@salesforce/lwc-jest` instead of `@salesforce/wire-service-jest-util`.

You also should not need to manually run `yarn add @salesforce/lwc-jest`. There is probably something funky with your Dockerfile. Do you see `@salesforce/lwc-jest` in your `node_modules` of the project where you run the tests? If not you aren't installing the dependency in the Dockerfile correctly. It's probably because of [this line](https://github.com/renatoliveira/lwc-jest-missing-module-demo/blob/master/Dockerfile#L6). That will globally install `lwc-jest`. Instead you should add it as a dependency to your project and install it locally there.

Also, the fact that one of your tests is passing but the others fail tells me it's probably differences in the test cases rather than an issue with this tool. On initial glance it looks like the first test is more accurately mocking the `fetch` API. In the first test before any individual test cases are run you do:
```
window.fetch = jest.fn().mockImplementation(() => Promise.resolve({
  json: () => Promise.resolve(serviceResponse)
}))
```
In the 4th test case I see you trying to override the global `fetch` API, but you do so after you push your component to the DOM and emit data through the wire-service-jest-util. The fetch call would have already been called by the time you set up this mock. 

Try updating the all tests to mock fetch more consistently and see if more tests pass.

**Comment by renatoliveira** [comment] 2019-07-20 15:24
Thank you very much for the clarification, @trevor-bliss.

The multiple tests are different because I thought the small differences might somehow be related to the missing module. I copied the original one and made the changes to see which one would work at the end. They all test basically the same thing. 

Regarding the installation on the Docker image: you are saying that in a CI pipeline I should always install lwc to run the tests? Couldn't it be installed globally so that the image can be reused for multiple projects without the need of running the install command?

**Comment by trevor-bliss** [comment] 2019-07-29 01:29
For CI and things like Docker images, I would highly recommend having this package be a dependency to your project and installing it locally rather than globally. Docker images should be self-contained and CI should be as reliable as possible. Having CI use packages that are globally installed make them less reliable since their versions will need to be managed outside of the regular CI flow.

Based on the code you shared it looks like these are problems specific to your code, not with sfdx-lwc-jest itself. I'm  closing the issue but if you think you find a bug in the package itself feel free to comment or file a new Issue.

**Closed by trevor-bliss** 2019-07-29 01:29 UTC

**Comment by renatoliveira** [comment] 2019-07-29 02:24
I still think it might have some kind of issue when running the globally installed version instead of a local one. Anyway, I switched to Yarn as our package manager. During the image build I can just add a `project.json` with the same dependencies as our project, and `yarn install` them during build, and store them in Yarn's cache. During build I can then use `yarn install --offline` so that it uses the cache version instead. So far so good, it is working.

Thank you for the patience and time to look at this "issue". :)
